#!/usr/bin/env python3
"""
Install the OpenClaw Pipe into Open WebUI.

Two modes:

1. **Bundle only** — generate a single-file bundle for manual paste::

       python3 install.py                           # stdout
       python3 install.py -o openclaw_pipe_bundle.py  # file

2. **Direct install** — push the bundle straight into a running
   Open WebUI instance via its REST API::

       python3 install.py \\
           --owui-url http://localhost:3000 \\
           --owui-key sk-xxxxxxxxxxxxxxxxxxxxxxxx

   This creates (or updates) the Pipe Function, sets Valves, and
   enables it — all in one command.  No browser needed.

The generated bundle has no local imports — everything is inlined in
dependency order.  Only external packages (pydantic, websockets,
opentelemetry) and stdlib imports remain at the top.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

REPO_DIR = Path(__file__).resolve().parent
FUNCTION_ID = "openclaw_pipe"
FUNCTION_NAME = "OpenClaw Pipe"

MODULES = [
    "valves.py",
    "protocol.py",
    "telemetry.py",
    "event_mapper.py",
    "gateway_client.py",
    "openclaw_pipe.py",
]

BUNDLE_HEADER = '''\
"""
OpenClaw Pipe Function for Open WebUI — bundled single-file distribution.

Generated by install.py.  This is a self-contained Pipe Function.
Configure Valves after installation.

Requirements in the Open WebUI Python environment:
    pydantic >= 2.0
    websockets >= 12.0
    opentelemetry-api, opentelemetry-sdk, opentelemetry-exporter-otlp (optional)
"""

from __future__ import annotations
'''

# ---------------------------------------------------------------------------
# Bundler
# ---------------------------------------------------------------------------

def read_module(path: Path) -> str:
    """Read a module, strip its docstring and local imports."""
    source = path.read_text(encoding="utf-8")
    source = _strip_module_docstring(source)
    source = _strip_local_imports(source)
    source = re.sub(r"\n{3,}", "\n\n", source)
    return source.strip()


def _strip_module_docstring(source: str) -> str:
    """Remove the module-level docstring (first triple-quoted block)."""
    lines = source.split("\n")
    result: list[str] = []
    in_docstring = False
    doc_done = False

    for line in lines:
        stripped = line.strip()
        if not doc_done and not in_docstring:
            if stripped.startswith('"""') or stripped.startswith("'''"):
                in_docstring = True
                if stripped.count('"""') >= 2 or stripped.count("'''") >= 2:
                    in_docstring, doc_done = False, True
                continue
        if in_docstring:
            if '"""' in stripped or "'''" in stripped:
                in_docstring, doc_done = False, True
            continue
        result.append(line)

    return "\n".join(result)


def _strip_local_imports(source: str) -> str:
    """Remove intra-package imports including parenthesized multi-line."""
    lines = source.split("\n")
    result: list[str] = []
    skip_until_close = False
    local_mods = tuple(m.replace('.py', '') for m in MODULES)

    for line in lines:
        stripped = line.strip()
        if skip_until_close:
            if ")" in stripped:
                skip_until_close = False
            continue
        is_local = any(
            re.match(rf"^from\s+\.?{m}\s+import\b", stripped)
            for m in local_mods
        ) or any(
            stripped == f"import {m}" or stripped.startswith(f"import {m} ")
            for m in local_mods
        )
        if is_local:
            if "(" in stripped and ")" not in stripped:
                skip_until_close = True
            continue
        result.append(line)

    return "\n".join(result)


def build_bundle() -> str:
    """Produce the bundled source."""
    parts = [BUNDLE_HEADER]
    for mod_name in MODULES:
        path = REPO_DIR / mod_name
        if not path.exists():
            print(f"❌ Missing: {path}", file=sys.stderr)
            sys.exit(1)
        src = read_module(path)
        sep = f"\n# {'─' * 60}\n# Inlined from {mod_name}\n# {'─' * 60}\n\n"
        parts.append(sep)
        parts.append(src)
        parts.append("\n")
    return "".join(parts)


def verify_bundle(source: str) -> bool:
    """Quick AST parse check."""
    import ast
    try:
        ast.parse(source)
        return True
    except SyntaxError as exc:
        print(f"❌ Bundle syntax error: {exc}", file=sys.stderr)
        return False


# ---------------------------------------------------------------------------
# Open WebUI API client (stdlib only — urllib)
# ---------------------------------------------------------------------------

class OWUIClient:
    """Minimal Open WebUI REST API client for Function management."""

    def __init__(self, base_url: str, api_key: str):
        self.base = base_url.rstrip("/")
        self.api = f"{self.base}/api/v1/functions"
        self._headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    def _req(self, method: str, path: str, body: dict | None = None) -> dict:
        url = f"{self.api}{path}"
        data = json.dumps(body).encode() if body else None
        req = urllib.request.Request(
            url, data=data, headers=self._headers, method=method,
        )
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read().decode())
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode(errors="replace")[:500]
            raise RuntimeError(
                f"OWUI API {method} {path} → {exc.code}: {detail}"
            ) from exc
        except urllib.error.URLError as exc:
            raise RuntimeError(
                f"Cannot reach Open WebUI at {self.base}: {exc.reason}"
            ) from exc

    def function_exists(self, fid: str) -> bool:
        """Return True if a function with *fid* already exists."""
        try:
            self._req("GET", f"/id/{fid}")
            return True
        except RuntimeError as exc:
            # Only treat 404 as "not found" — surface auth/server errors.
            if "404" in str(exc):
                return False
            raise

    def create_or_update(self, fid: str, content: str, meta: dict | None = None) -> dict:
        """Create or update a Pipe Function with *content* as its source."""
        meta = meta or {}
        meta.setdefault("name", FUNCTION_NAME)
        meta.setdefault("description", "OpenClaw agents as selectable models.")
        body = {"id": fid, "content": content, "meta": meta}
        if self.function_exists(fid):
            print(f"   ↳ Updating existing function '{fid}' ...", file=sys.stderr)
            return self._req("POST", f"/id/{fid}/update", body)
        print(f"   ↳ Creating new function '{fid}' ...", file=sys.stderr)
        return self._req("POST", "/create", body)

    def set_valves(self, fid: str, valves: dict) -> dict:
        """Set admin-level Valves for *fid*."""
        return self._req("POST", f"/id/{fid}/valves/update", valves)

    def enable(self, fid: str) -> dict:
        """Toggle the function on (idempotent)."""
        return self._req("POST", f"/id/{fid}/toggle")


# ---------------------------------------------------------------------------
# Valves helpers
# ---------------------------------------------------------------------------

def _interactive_valves() -> dict[str, str]:
    """Prompt the user for minimum required valves."""
    print("\n🔧 Configure Valves (press Enter to accept defaults):", file=sys.stderr)
    print(
        "   At minimum you need GATEWAY_TOKEN.  GATEWAY_URL defaults to\n"
        "   ws://127.0.0.1:18789 (loopback).\n"
        "\n"
        "   💡 You can change any of these later in the Open WebUI admin:\n"
        "      Workspace → Functions → ⚙️ (gear icon next to OpenClaw Pipe)\n"
        "      No restart needed — valves are live-reloaded on each request.",
        file=sys.stderr,
    )
    print()

    def _ask(prompt: str, default: str = "") -> str:
        d = f" [{default}]" if default else ""
        try:
            val = input(f"   {prompt}{d}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n   ⏭️  Skipped.", file=sys.stderr)
            return default
        return val or default

    valves: dict[str, str] = {}
    gw_url = _ask("GATEWAY_URL", "ws://127.0.0.1:18789")
    if gw_url:
        valves["GATEWAY_URL"] = gw_url
    gw_token = _ask("GATEWAY_TOKEN")
    if gw_token:
        valves["GATEWAY_TOKEN"] = gw_token
    prefix = _ask("AGENT_PREFIX", "OpenClaw/")
    if prefix and prefix != "OpenClaw/":
        valves["AGENT_PREFIX"] = prefix
    agent_list = _ask("AGENT_LIST", "__auto__")
    if agent_list and agent_list != "__auto__":
        valves["AGENT_LIST"] = agent_list
    approval = _ask("APPROVAL_MODE", "auto_deny")
    if approval and approval != "auto_deny":
        valves["APPROVAL_MODE"] = approval

    print()
    return valves


def load_valves(raw: str) -> dict:
    """Parse a Valves dict from a JSON literal or ``@file`` reference."""
    raw = raw.strip()
    if raw.startswith("@"):
        path = Path(raw[1:]).expanduser()
        if not path.exists():
            print(f"❌ Valves file not found: {path}", file=sys.stderr)
            sys.exit(1)
        return json.loads(path.read_text())
    return json.loads(raw)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install the OpenClaw Pipe into Open WebUI.",
    )
    # Output
    parser.add_argument(
        "-o", "--output", metavar="PATH",
        help="Write bundle to PATH (default: print to stdout).",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Only verify that the bundle parses.",
    )
    # Direct install
    parser.add_argument(
        "--owui-url", metavar="URL",
        help="Open WebUI base URL (e.g. http://localhost:3000).",
    )
    parser.add_argument(
        "--owui-key", metavar="KEY",
        help="Open WebUI admin API key (Bearer token).",
    )
    parser.add_argument(
        "--owui-id", metavar="ID", default=FUNCTION_ID,
        help=f"Function ID in OWUI (default: {FUNCTION_ID}).",
    )
    parser.add_argument(
        "--valves", metavar="JSON",
        help='Valves JSON literal, or @path/to/valves.json.  '
             'If omitted in direct-install mode and stdin is a terminal, '
             'you are prompted interactively.',
    )
    parser.add_argument(
        "--no-interactive", action="store_true",
        help="Skip interactive prompts (fail if required valves are missing).",
    )
    args = parser.parse_args()

    direct = bool(args.owui_url and args.owui_key)
    output = bool(args.output)
    check_only = args.check

    # ── Build bundle ──────────────────────────────────────────────
    print("📦 Bundling OpenClaw Pipe ...", file=sys.stderr)
    bundle = build_bundle()
    if not verify_bundle(bundle):
        sys.exit(1)
    print(f"   ✅ Bundle: {len(bundle):,} bytes (~{bundle.count(chr(10))} lines)", file=sys.stderr)

    if check_only:
        sys.exit(0)

    # ── Direct install to OWUI ────────────────────────────────────
    if direct:
        client = OWUIClient(args.owui_url, args.owui_key)

        print(f"\n🔑 Authenticating to {args.owui_url} ...", file=sys.stderr)
        try:
            client.create_or_update(args.owui_id, bundle)
        except RuntimeError as exc:
            print(f"❌ {exc}", file=sys.stderr)
            sys.exit(1)
        print(f"   ✅ Function '{args.owui_id}' installed.", file=sys.stderr)

        # Valves
        if args.valves:
            valves = load_valves(args.valves)
        elif sys.stdin.isatty() and not args.no_interactive:
            valves = _interactive_valves()
        else:
            valves = None

        if valves:
            print(f"   ↳ Setting {len(valves)} valve(s) ...", file=sys.stderr)
            try:
                client.set_valves(args.owui_id, valves)
                print("   ✅ Valves configured.", file=sys.stderr)
            except RuntimeError as exc:
                print(f"   ⚠️  Valve update failed: {exc}", file=sys.stderr)
        else:
            print(
                "   💡 Pass --valves '{\"GATEWAY_URL\":\"...\",\"GATEWAY_TOKEN\":\"...\"}' "
                "to configure.",
                file=sys.stderr,
            )

        # Enable
        try:
            client.enable(args.owui_id)
            print(f"   ✅ Function enabled.", file=sys.stderr)
        except RuntimeError as exc:
            print(f"   ⚠️  Enable toggle failed: {exc}", file=sys.stderr)

        print(f"\n✅ Done.  Select 'OpenClaw/Default' in the model selector.", file=sys.stderr)
        return

    # ── File output ───────────────────────────────────────────────
    if output:
        Path(args.output).write_text(bundle, encoding="utf-8")
        print(f"✅ Written to {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(bundle)


if __name__ == "__main__":
    main()
